site_name: MkDocs Material
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.tabs.annotation
    - content.tabs.copy
  language: en
  palette:
    - scheme: userDocs
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Dark Mode
      primary: custom
    - scheme: darkMode
      toggle:
        icon: material/toggle-switch
        name: Switch to Light Mode
      primary: custom
      accent: custom

extra_css:
  - assets/styles/extra.css

markdown_extensions:
  - def_list
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/allison-dahan
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/

